# bootstrap.ignore_system_bootstrap_checks: true
transport.host: 0.0.0.0
http.host: 0.0.0.0
discovery.zen.minimum_master_nodes: 1

network.host:
- _local_
- _site_

network.publish_host: _local_

cluster.name: elasticsearch